Export comptable
icysoft/dolibarr pull request #2
Opened 2019-11-28 16:15 UTC by CorentinDurey

# New: Ajout d'un module pour exporter en fichier excel les facture
* Mise à jour du module PhpSpreadSheet
* Ajout du module Avoloi export qui réceptionne les appels ver l'api
* Ajout de la classe "create spreadsheet" qui s'occupe de manipuler les spreadsheets
* Le reste viens de la mise à jours de PhpSpreadSheet

2019-12-09 14:11 UTC, Ballrock requested changes
Quelques retours de mon coté, et on va dire YOLO pour le composer on regardera a terme ;)

2019-12-09 14:11 UTC, Ballrock commented on htdocs/avoloiexport/class/api_avoloiexport.class.php
> +			throw new RestException(405, "Missing field");
Ici c'est plutôt une HTTP 400. Pour info : 
- 400 | Bad Request | La syntaxe de la requête est erronée.
- 405 | Method Not Allowed | Méthode de requête non autorisée

2019-12-09 14:11 UTC, Ballrock commented on htdocs/avoloiexport/class/api_avoloiexport.class.php
> +	 * @throws 200
Sauf erreur de ma part en lisant le code, il ne peut renvoyer que une HTTP 200.
Deux solutions à ça : soit, nettoyer les throws de la PHPDoc, pour que cela corresponde, soit modifier ta gestion d'erreur pour qu'elle renvoie des erreurs HTTP.

2019-12-09 14:11 UTC, Ballrock commented on htdocs/avoloiexport/class/api_avoloiexport.class.php
> +	 * @throws 200
Idem, commentaire précédent, ne revoit que une 200 ou 405 (400 après la modification)

2019-12-09 14:11 UTC, Ballrock commented on htdocs/avoloiexport/class/api_avoloiexport.class.php
> +			&& ($timestamp >= ~PHP_INT_MAX) && strlen($timestamp) === 10;
Euhhhh t'a vraiment besoin de verifier de cette manière la validité d'un timestamp ?
Concrètement cette fonction rend valide des timestamps négatif...

Le premier test de conversion est pas mal, l'inférieur à PHP_INT_MAX et la taille du timestamp à la limite, par contre verifier via l'opérateur negatif binaire "~" si il est pas inférieur à la taille max d'un INT signé... selon le besoin métier je pense qu'un >= 0 aurait largement fait le taff.

2019-12-09 14:11 UTC, Ballrock commented on htdocs/avoloiexport/class/avoloi_export.modules.php
> +}
Niquel d'avoir gagné la classe sans rien.

2019-12-09 14:11 UTC, Ballrock commented on htdocs/avoloiexport/class/create_spreadsheet.class.php
> +                throw new RestException(405, "Wrong field format");
Idem pour le code retour http : 405 -> 400

2019-12-09 14:11 UTC, Ballrock commented on htdocs/avoloiexport/class/create_spreadsheet.class.php
> +        if ($objets_ret && count($objets_ret) > 0) {
Le count `count($objets_ret) > 0` est inutile ici, le foreach ne fera rien si le tableau est vide

2019-12-09 14:11 UTC, Ballrock commented on htdocs/avoloiexport/class/create_spreadsheet.class.php
> +                if ($facture && $facture->lines && count($facture->lines) > 0) {
Idem pour `&& count($facture->lines) > 0`

2019-12-09 14:11 UTC, Ballrock commented on htdocs/avoloiexport/class/create_spreadsheet.class.php
> +        if ($objets_ret && count($objets_ret) > 0) {
idem `&& count($objets_ret) > 0`

2019-12-09 14:11 UTC, Ballrock commented on htdocs/avoloiexport/class/create_spreadsheet.class.php
> +                if ($pathtemp !== '') {
Pas de `else`ici, tu peux donc combiner les `if`

2019-12-19 16:47 UTC, CorentinDurey commented
Tout à été changé.

2019-12-27 15:53 UTC, merged