feat:UC26 et UC21 paramétrage de la tva
icysoft/dolibarr pull request #3
Opened 2019-11-28 16:29 UTC by CorentinDurey

# New Ajout gestion des valeurs de tva pour le clients
* Ajout de la récupération du champ $taux_tva_default
* Ajout de la fonction getTauxTva qui récupère la liste des taux de tva possible
* Ajout de la fonciton addTauxTva qui ajoute une nouvelle entrée de tva dans la liste des taux de tva possible

2019-12-09 14:00 UTC, Ballrock requested changes
Corentin, c'est niquel à part deux petits points de doc et de code reponse http

2019-12-09 14:00 UTC, Ballrock commented on htdocs/avoloisetup/class/api_avoloisetup.class.php
> +	 * @throws 200
Sauf erreur de ma part en lisant le code, il ne peut renvoyer que une HTTP 200.  
Deux solutions à ça : soit, nettoyer les throws de la PHPDoc, pour que cela corresponde, soit modifier ta gestion d'erreur pour qu'elle renvoie des erreurs HTTP.

2019-12-09 14:00 UTC, Ballrock commented on htdocs/avoloisetup/class/api_avoloisetup.class.php
> +			throw new RestException(405, 'Le taux est manquant');
Ici c'est plutôt une HTTP 400. Pour info : 
- 400 | Bad Request | La syntaxe de la requête est erronée.
- 405 | Method Not Allowed | Méthode de requête non autorisée

2019-12-09 14:00 UTC, Ballrock commented on htdocs/avoloisetup/class/api_avoloisetup.class.php
> +			throw new RestException(405, 'Le libelle est manquant');
Idem HTTP 400 ici

2019-12-09 14:00 UTC, Ballrock commented on htdocs/avoloisetup/class/api_avoloisetup.class.php
> +			throw new RestException(405, 'Le taux ne peut pas être infèrieur à 0');
Idem HTTP 400 ;)

2019-12-09 14:00 UTC, Ballrock commented on htdocs/avoloisetup/class/api_avoloisetup.class.php
> +	 * @throws 200
Il faudrait nettoyer la php doc, je pense que c'est un copier-coller le l'API précédente

2019-12-19 16:32 UTC, CorentinDurey commented on htdocs/avoloisetup/class/api_avoloisetup.class.php
> +	 * @throws 200
J'ai modifié

2019-12-19 16:32 UTC, CorentinDurey commented on htdocs/avoloisetup/class/api_avoloisetup.class.php
> +			throw new RestException(405, 'Le taux ne peut pas être infèrieur à 0');
J'ai modifié

2019-12-19 16:32 UTC, CorentinDurey commented on htdocs/avoloisetup/class/api_avoloisetup.class.php
> +			throw new RestException(405, 'Le libelle est manquant');
J'ai modifié

2019-12-19 16:33 UTC, CorentinDurey commented on htdocs/avoloisetup/class/api_avoloisetup.class.php
> +			throw new RestException(405, 'Le taux est manquant');
J'ai modifié

2019-12-19 16:33 UTC, CorentinDurey commented on htdocs/avoloisetup/class/api_avoloisetup.class.php
> +	 * @throws 200
J'ai modifié

2019-12-27 15:55 UTC, merged